apiVersion: 1

datasources:
  - name: CSPM Postgres
    type: postgres
    access: proxy
    url: ${GF_DB_HOST}:5432
    database: ${GF_DB_NAME}
    user: ${GF_DB_USER}
    isDefault: true
    editable: true
    secureJsonData:
      password: ${GF_DB_PASSWORD}
    jsonData:
      sslmode: require
      postgresVersion: 1600
      timescaledb: false
